### ISSUE TITLE
RE 2.0 Can't upgrade large windows

### ISSUE THREAD

**Issue by Grabber48** [Vollinger0/vscode-ecf-support#1]
Every other bock on CV can be upgraded with a multitool except large windows. Small windows on an SV can be. Sorry if this isn't the correct place would appreciate a link to the proper page if you know one. Thanks

**Comment by Vollinger0** [comment]
This is definitely the wrong place for RE2-questions ;)
Try the discussion forum on steam: https://steamcommunity.com/sharedfiles/filedetails/discussions/2550354956
the forums from empyrion: https://empyriononline.com/threads/reforged-eden-scenario.94773/
or the official discord: https://discord.gg/empyrion
